# Generated by Django 4.1.3 on 2022-12-01 06:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="users",
            field=models.ManyToManyField(
                related_name="announcements", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
