# Generated by Django 4.1.3 on 2022-12-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_announcement_pub_date_announcement_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="users",
        ),
    ]
