# Generated by Django 4.1.3 on 2022-12-01 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0003_remove_announcement_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="suscribers",
            field=models.ManyToManyField(
                blank=True, related_name="suscribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
