# Generated by Django 4.1.3 on 2022-12-02 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0007_alter_announcement_topics_alter_userprofile_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="topics",
            field=models.ManyToManyField(related_name="announcements", to="main.topic"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="suscribers",
            field=models.ManyToManyField(
                blank=True, related_name="topics", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="topics",
            field=models.ManyToManyField(related_name="users", to="main.topic"),
        ),
    ]
