# Generated by Django 4.1.3 on 2022-12-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_user_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="topics",
            field=models.ManyToManyField(related_name="topics", to="main.topic"),
        ),
    ]
