# Generated by Django 4.1.3 on 2022-12-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_announcement_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="topics",
            field=models.ManyToManyField(related_name="post_topics", to="main.topic"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="topics",
            field=models.ManyToManyField(related_name="user_topics", to="main.topic"),
        ),
    ]
